onfido/onfido-openapi-spec

README.md

Adds "Support" h2 and caveat about supporting user-generated libraries

More information about support

---

README.md

We now provide a custom-built one

Remove link to Java library

---

openapi.yaml
paths/checks.yaml
schemas/checks/check.yaml

- Add `webhook_ids` 
- Add download check PDF endpoint

API v3.1 additions

---

README.md
openapi.yaml
schemas/reports/document_CDQ_reasons.yaml
schemas/reports/document_IQ_reasons.yaml
schemas/reports/document_ODP_reasons.yaml
schemas/reports/document_breakdown.yaml
schemas/reports/document_properties.yaml
schemas/reports/facial_similarity_photo_breakdown.yaml
schemas/reports/facial_similarity_video_breakdown.yaml
schemas/reports/identity_enhanced_breakdown.yaml
schemas/reports/identity_enhanced_properties.yaml
schemas/reports/known_faces_breakdown.yaml
schemas/reports/known_faces_properties.yaml
schemas/reports/photo_fully_auto_breakdown.yaml
schemas/reports/photo_reasons.yaml
schemas/reports/proof_of_address_breakdown.yaml
schemas/reports/proof_of_address_properties.yaml
schemas/reports/report.yaml
schemas/reports/right_to_work_breakdown.yaml
schemas/reports/right_to_work_properties.yaml
schemas/reports/video_reasons.yaml
schemas/reports/watchlist_enhanced_breakdown.yaml
schemas/reports/watchlist_enhanced_properties.yaml
schemas/reports/watchlist_standard_breakdown.yaml
schemas/reports/watchlist_standard_properties.yaml

* Adds report response schemas

OpenApi specification expansion (beta)

---

README.md
openapi.yaml
output.json
schemas/reports/photo_auto_reasons.yaml
schemas/reports/photo_fully_auto_breakdown.yaml

Adding `output.json` and small fixes

Add output.json

---

README.md
openapi.yaml
output.json
schemas/checks/check.yaml
schemas/reports/document_breakdown.yaml
schemas/reports/document_properties.yaml
schemas/reports/facial_similarity_photo_breakdown.yaml
schemas/reports/facial_similarity_video_breakdown.yaml
schemas/reports/photo_fully_auto_breakdown.yaml
schemas/reports/report.yaml

* change base_url to use API v3.2
* add new features introduced in API v3.2
* update output.json file

Update to support API v3.2

---

openapi.yaml
output.json
paths/ping.yaml

Adding [the Ping endpoint](https://documentation.onfido.com/#ping) to the OpenAPI specification. 
Requested [here](https://github.com/onfido/onfido-openapi-spec/issues/19)

Add Ping endpoint 

---

openapi.yaml
output.json
paths/documents.yaml
paths/workflow_runs.yaml
schemas/applicants/applicant.yaml
schemas/location/location.yaml
schemas/tasks/task.yaml
schemas/workflow_runs/workflow_run.yaml

The specification has been updated to API v3.4, including the workflow run endpoints.

Update to v3.4 including Workflow endpoints

---

openapi.yaml
output.json
paths/workflow_runs.yaml
schemas/workflow_runs/workflow_runs_list.yaml

Updated the spec to include the List Workflow Runs endpoint

added List Workflow Runs endpoint

---

openapi.yaml
paths/tasks.yaml
paths/workflow_runs.yaml
schemas/workflow_runs/workflow_runs_list.yaml

* fix response schema of `/workflow_runs`
* fix declaration of `complete_task` endpoint

Tweaks to the studio spec

---

schemas/reports/document_report.yaml
schemas/reports/facial_similarity_photo_report.yaml
schemas/reports/facial_similarity_video_report.yaml
schemas/reports/identity_enhanced_report.yaml
schemas/reports/known_faces_report.yaml
schemas/reports/photo_fully_auto_report.yaml
schemas/reports/proof_of_address_report.yaml
schemas/reports/report.yaml
schemas/reports/right_to_work_report.yaml
schemas/reports/watchlist_enhanced_report.yaml
schemas/reports/watchlist_standard_report.yaml

as codegen tools seem to have a hard time generating code from the former.

replace oneOf usage with discriminators for report polymorphism

---

schemas/tasks/task.yaml

task_def_version and workflow_run_id were missing.

adding missing references to task schema

---

.github/workflows/update-specs-and-client-libraries.yaml
shell/generate.sh

Put back CI secret to previous name after DevOps Test

Update CI and retrieve last (even if unpublished) version from library

---

.github/workflows/update-specs-and-client-libraries.yaml

- Allow overriding spec version
- Put prettier back for linting .md files

[CAT-1120] Small improvement and fix to github action workflow

---

schemas/webhooks/webhook_event.yaml

Add missing `started_at_iso8601` property in webhook event's object.

Add started_at_iso8601 field in webhook event

---

schemas/workflow_runs/definitions.yaml

✨ Expose `customer_user_id` in `workflow_runs`

---

schemas/workflow_runs/definitions.yaml

"sdk_token" exposed the studio sdk token for v3.6 API.

adding sdk_token to workflow run schema

---

generators/typescript-axios/templates/apiInner.mustache
generators/typescript-axios/templates/package.mustache

Fixing error raised when uploading medias including location data raised in https://github.com/onfido/onfido-node/pull/141
Take the opportunity to increase minimum Axios version to solve dependabot alert https://github.com/onfido/onfido-node/security/dependabot/58

Fix error raised when uploading media with location in typescript

---

generators/python/urllib3/templates/SHA256SUM
generators/python/urllib3/templates/api_client.mustache
shell/sync-lib.sh

Don't remove brand new `MIGRATION.md` files in client libraries and persist change in https://github.com/onfido/onfido-python/pull/73.

Keep MIGRATION.md and add template for python generator patch

---

paths/workflow_runs.yaml

This MR adds a new param applicant_id in GET /workflow_runs

add applicant_id in GET /workflow_runs

---

schemas/webhooks/webhook_event.yaml

Add  customer_user_id to the webhook event.

Add customer_user_id inside webhook event resource

---

generators/ruby/faraday/templates/Gemfile.mustache

Make change in https://github.com/onfido/onfido-ruby/pull/72/commits/364253f4b17560cbbcb60554154b063d3db140f1 persistent

Update ruby dev dependency

---

openapi.yaml
paths/applicants.yaml
schemas/applicants/definitions.yaml

Creating GET applicant consents endpoint.

CAT-1760: create get applicant consents endpoint

---

generators/ruby/faraday/templates/README.mustache

Persist change in https://github.com/onfido/onfido-ruby/pull/79

Update Ruby library README template

---

generators/java/okhttp-gson/templates/README.mustache
generators/java/okhttp-gson/templates/libraries/okhttp-gson/pom.mustache

Persist changes in PRs below:
- https://github.com/onfido/onfido-java/pull/154
- https://github.com/onfido/onfido-java/pull/155
- https://github.com/onfido/onfido-java/pull/156
- https://github.com/onfido/onfido-java/pull/157

Persist onfido-java publishing to Central Publisher Portal
