schemas/reports/report.yaml

Report schema is missing a reference to the check_id

Fix report schema file to refer to check_id

---

openapi.yaml
paths/live_videos.yaml
schemas/checks/check.yaml

Adding:
- download live video frame endpoint
- ability to trigger pre-determined response for Document report sub-result 
- ability to trigger pre-determined consider for multiple report checks
- privacy_notices_read_consent_given parameter

Add download live video frame, sub-result and consider pre-determined sandbox responses and privacy consent parameter

---

README.md
schemas/reports/right_to_work_breakdown.yaml

- Add breakdown for right to work report using a GOV.UK right to work share code

Add RTW share code breakdown

---

schemas/reports/document_with_driver_verification_report.yaml

A new `passenger_vehicle` property for the driver_verification Document report variant

Adding `passenger_vehicle` property to the driver_verification report

---

.github/workflows/generate-single-openapi-spec.yaml
.gitignore
README.md
generator/configuration/common.yaml
generator/script/generate.sh
generator/templates/openapi-yaml/.openapi-generator-ignore
generator/templates/openapi/.openapi-generator-ignore
openapi.yaml
schemas/workflow_runs/definitions.yaml
schemas/workflow_runs/workflow_run_builder.yaml

Initial version of Github Action workflow to build and push single-file OpenAPI specification.
Include validation of multi file specification and a few files which were forgotten in [PR#42](https://github.com/onfido/onfido-openapi-spec/pull/42).

Add github action to generate single API spec

---

.github/workflows/generate-single-openapi-spec.yaml

We can avoid checking not being in a forked repository, since workflow in forked repository are disabled by default:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories-1
Moreover anticipating this fix to be sure targeting good branch:
https://github.com/actions/checkout/issues/317#issuecomment-1221335371

Fix condition to trigger GitAction workflow (2)

---

.github/workflows/single-file-openapi-spec.yaml

- Add access token retrieval to grant Github action the right of pushing to master branch (same repository)
- Don't trigger workflow in case of changes to `generated/artifacts` (to allow being triggered in loop)
- A few minor changes

Improve workflow to generate single-file OpenAPI spec

---

.github/workflows/update-specs-and-client-libraries.yaml

Rationale behind this is that we cannot do anything to fix the change when pre-commit. Instead we should fix that:
- by creating a new PR to onfido-openapi-spec, if fix is needed in the github actions command
- by amending auto-generated PR to onfido-* client lib, if fix is needed in the library

Ignore preCommit script result (and remove some debug prints)

---

.github/workflows/update-specs-and-client-libraries.yaml
.gitignore
shell/postman-openapi-refresh.py

With this change we're going to automatically adding to each endpoint's method a proper tag to allow categorisation in Postman:
```sh
grep 'tags": \[' generated/artifacts/openapi-postman/openapi.json | uniq 
"tags": ["Core | Applicants"]
"tags": ["Core | Documents"]
"tags": ["Core | Live photos"]
"tags": ["Core | Live videos"]
"tags": ["Core | Workflow Runs"]
"tags": ["Core | Motion captures"]
"tags": ["Core | Monitors"]
"tags": ["Core | ID Photos"]
"tags": ["Others | Ping"]
"tags": ["Others | Webhooks"]
"tags": ["Others | Address Picker"]
"tags": ["Others | Generate SDK Token"]
"tags": ["Others | Repeat attempts"]
"tags": ["Others | Autofill"]
"tags": ["Others | Fraud reporting (ALPHA)"]
"tags": ["Others | Checks"]
"tags": ["Others | Reports"]
```
This script will be automatically …

[CAT-1146] Generate OpenAPI spec with tags to publish Postman collection

---

generators/typescript-axios/templates/package.mustache

This change comes after [PR#109](https://github.com/onfido/onfido-node/pull/109)

Add dotenv dependency in package.mustache for typescript-axios

---

.github/workflows/update-specs-and-client-libraries.yaml
generators/typescript-axios/config.yaml
generators/typescript-axios/templates/package.mustache
shell/patch-openapi-definition.py

Small improvements to CHANGELOG file entry generation ([example](https://github.com/onfido/onfido-openapi-spec/actions/runs/8972513621/job/24640687737)):
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index db9e953..3a854bb 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,5 +1,9 @@
+## v4.0.0 6th May 2024
+
+- Refresh library up to commit: [cb6cc84](https://github.com/onfido/onfido-openapi-spec/commit/cb6cc84c6a52185d7cbf1f7672afe5803915272f)
+
```
Include a few updates to typescript/axios package.json template after:
- https://github.com/onfido/onfido-node/pull/116
- https://github.com/onfido/onfido-node/pull/119
It calls `npx prettier` to improve formats of some generated files (package.json for typescript/axios and README.md files) and to Postman collection generation to create the …

[CAT-1120] Some improvements to CI, Postman collection generation and typescript/axios templates

---

generators/ruby/faraday/templates/webhook_event_verifier.mustache

Read payload already receives the payload content.

CAT-1068: fix webhook verifier logic

---

.github/workflows/update-specs-and-client-libraries.yaml
paths/watchlist_monitors.yaml
schemas/watchlist_monitors/definitions.yaml
schemas/watchlist_monitors/watchlist_monitor_builder.yaml
schemas/watchlist_monitors/watchlist_monitor_matches_list.yaml
schemas/watchlist_monitors/watchlist_monitor_matches_updater.yaml

Improve and fix definition to match [watchlist_monitor endpoints](https://documentation.onfido.com/#create-monitor-request-body) behaviour. Main improvements:
- Create a watchlist_monitor_builder
- Rename `update_monitor_match` into `update_watchlist_monitor_match`
It includes a change in CI asked by DevOps.

[CAT-1120] Fix watchlist_monitors schemas

---

generators/java/okhttp-gson/templates/libraries/okhttp-gson/oneof_model.mustache
generators/java/okhttp-gson/templates/libraries/okhttp-gson/pom.mustache
paths/tasks.yaml
schemas/tasks/complete_task_builder.yaml

- OpenAPI spec updates:
- Rename objects returned from list_tasks method from `task` to `task_item` to avoid collision with the `task` object returned by the find_task method
- Rename `Complete Task Builder Data` schema into `Complete Task Data Builder` for consistency
- Swap List and Object to have proper order in generated code (from less to more specific, in Java at least)
- Java Templates updates:
- include missing java.util.UUID import into oneof_model template
- extract Objects and Lists included in a oneOf schema as `JsonElement` instead of `JsonPrimitive` (a _java.lang.IllegalStateException: Not a JSON Primitive_ exception would be raised otherwise) -> a PR to openapi generator will possibly be created
- fix to pom.xml template to remove duplicated block closures

[CAT-1120] Some fixes to OpenAPI spec and java templates

---

generators/java/okhttp-gson/templates/README.mustache
generators/php/templates/README.mustache
generators/python/urllib3/templates/README.mustache
generators/ruby/faraday/templates/README.mustache
generators/typescript-axios/templates/README.mustache
paths/id_photos.yaml
schemas/tasks/definitions.yaml

Rename schema returned by `list_id_photos` operation from `ID Photos list` into `Id Photos list` for consistency as discussed in https://github.com/onfido/onfido-python/pull/58#issuecomment-2145156354.
Taking also the opportunity for replacing hardcoded value for webhook verification token inside templated README.md files into a value retrieved from environment.
Lastly fixing also warning below raised when running [ruby integration tests](https://github.com/onfido/onfido-ruby/actions/runs/9366368764/job/25783635293):
`warning: character class has '-' without escape: /^[0-9a-z-_]+$/`

[CAT-1120] Improve readme, fix id photos list and regex in tasks definition

---

schemas/reports/facial_similarity_motion_properties.yaml
schemas/reports/facial_similarity_motion_report.yaml
schemas/reports/facial_similarity_photo_fully_auto_properties.yaml
schemas/reports/facial_similarity_photo_fully_auto_report.yaml
schemas/reports/facial_similarity_photo_properties.yaml
schemas/reports/facial_similarity_photo_report.yaml
schemas/reports/facial_similarity_video_properties.yaml
schemas/reports/facial_similarity_video_report.yaml
shell/publish-postman-collection.py

- Add missing `properties` field in `facial_similarity_*` reports
- Patch generated Postman collection to properly generate upload endpoints (while waiting for https://github.com/postmanlabs/openapi-to-postman/issues/795's resolution)

[CAT-1120] Improve facial similarity fully auto report and fix Postman collection

---

generators/java/okhttp-gson/config.yaml
generators/java/okhttp-gson/templates/FileTransfer.mustache
generators/java/okhttp-gson/templates/OnfidoInvalidSignatureError.mustache
generators/java/okhttp-gson/templates/SHA256SUM
generators/java/okhttp-gson/templates/WebhookEventVerifier.mustache
generators/java/okhttp-gson/templates/libraries/okhttp-gson/ApiClient.mustache
generators/java/okhttp-gson/templates/libraries/okhttp-gson/api.mustache
generators/java/okhttp-gson/templates/libraries/okhttp-gson/oneof_model.mustache

To allow in-memory file download, a new object `FileTransfer` has created for Java Client library.
It includes some changes to templates to integrate such object, and a few fix and improvement.
This new `FileTransfer` object allows uploading/downloading a file from/to disk or from memory.
It also adds `getStatus()` method to generic Report object for Java.
Preview of changes we're going to have in client library is below:
https://github.com/onfido/onfido-java/compare/in-memory-file-transfer

[CAT-1241][Java] Add FileTransfer object to allow in-memory only file upload/download

---

.github/workflows/update-specs-and-client-libraries.yaml
generators/java/okhttp-gson/templates/FileTransfer.mustache
generators/ruby/faraday/config.yaml
generators/ruby/faraday/templates/README.mustache
shell/generate.sh
shell/sync-lib.sh

- add pre-commit command to `sync-lib.sh` script and call it from CI
- run `sync-lib.sh` within a docker image when needed
- allow to override the version of the generated library
- small Fix in one FileTransfer (java) method comment
- fix library in Ruby generated library (includes generated `README.md`)

[CAT-1120] Update generate script and allow overriding library version

---

.github/workflows/update-specs-and-client-libraries.yaml
generators/python/urllib3/config.yaml
generators/python/urllib3/templates/README.mustache
generators/python/urllib3/templates/pyproject.mustache

Spec tag wasn't correctly retrieved in CI (e.g. [here](https://github.com/onfido/onfido-openapi-spec/actions/runs/9641340543/job/26586831612)):
```
SOURCE_VERSION=
SOURCE_VERSION=${SOURCE_VERSION:-}
```
This was due to the fact actions/checkout@v4 plugin wasn't fetching tags.
Taking the opportunity for fixing also the package distribution name in python library's README.

[CAT-1120] Fix tags retrieval in CI + python README.md

---

generators/java/okhttp-gson/templates/README.mustache
generators/php/templates/README.mustache
generators/python/urllib3/templates/README.mustache
generators/ruby/faraday/templates/README.mustache
generators/typescript-axios/templates/README.mustache

Just spotted out that in [Ruby README.md](https://github.com/onfido/onfido-ruby/blob/master/README.md) we've a broken link (pointing to [trevis CI](https://app.travis-ci.com/onfido/onfido-ruby)).
Taking the opportunity to add fury.io (when available) and github build status badge in all languages README.md files.

Add/update badges in generated README.md files

---

openapi.yaml
paths/qualified_electronic_signature.yaml
shell/patch-openapi-definition.py

Add the endpoint described [here](https://documentation.onfido.com/api/latest/#retrieve-workflow-run-signed-document) to the OpenAPI spec

chore(qes): add documents endpoint

---

schemas/webhooks/webhook_event.yaml

As reported `id` property (inside `object`) is not an uuid, therefore uuid format needs to be removed.

[CAT-1297] Webhook Event: remove uuid format from object.id

---

schemas/documents/definitions.yaml

Hi,
as I can't open issues here, I need to open a PR :-) 
(this PR shouldn't be merged like this of course)
When requesting documents that the WebSDK uploaded, they have a file_type of "jpeg". The OpenAPI spec however only lists "jpg" as allowed value.
Somehow this should be adapted as your API is not working according to the specification.
Example response from the api:
```
GET https://api.eu.onfido.com/v3.6/documents/2e503b6a-99c6-4829-802b-9e43903b7c22
{
"applicant_id": "ce61a2a3-4190-43d2-b634-e7bdabad760b",
"id": "2e503b6a-99c6-4829-802b-9e43903b7c22",
"file_name": "document_back.jpeg",
"file_type": "jpeg",
"file_size": 2610325,
[...]
}
```
Thanks, Christoph

add jpeg file type for documents

---

README.md
generators/ruby/faraday/templates/README.mustache

- Add to README.md swagger link to read OpenAPI specification from repository
- Persist in template change to ruby README.md file in https://github.com/onfido/onfido-ruby/pull/59

Update README.md files

---

shell/publish-postman-collection.py

Fixing authentication header in the generated postman collection, by replacing `{{apiKey}}` with the expected format: `Token token={{apiToken}}`.
Taking the opportunity for removing some temporary patching code, not needed anymore after closure of the ticket https://github.com/postmanlabs/openapi-to-postman/issues/795 (solved by [PR#805](https://github.com/postmanlabs/openapi-to-postman/pull/805)).

[CAT-1339] Fix authorization header in Postman collection

---

generators/php/templates/Configuration.mustache

The `setRegion()` method in PHP expects an instance of the `Region` enum, however the PHPDoc comment states that it requires a `string`, this means that static analysis and IDEs complain when calling it, but it works correctly. However, if you pass a `string` it fails because the `->name` property does not exist.

fix: resolve `setRegion` method argument in PHP

---

generators/ruby/faraday/templates/gemspec.mustache

the current version of the `onfido-ruby` repository requires `faraday-follow-redirects`, but the gemspec generated by this project doesn't include it.
This causes our Rails project to fail when loading onfido configuration due to [this line](https://github.com/onfido/onfido-ruby/blob/b49ddfe50718a84fb3b054312bc31042d31e4ec6/lib/onfido/configuration.rb#L13). 
I expect this would be a problem for most anyone using the latest version of `onfido-ruby`.

Including `faraday-follow_redirects` as a runtime dependency in ruby

---

schemas/address/definitions.yaml
schemas/applicants/definitions.yaml
schemas/extractions/extraction.yaml
schemas/us_driving_licence/definitions.yaml

Fix pattern (regex) definitions for a few fields to make example being shown in postman collection.

Fix OpenAPI pattern definitions to improve Postman experience

---

generators/typescript-axios/templates/README.mustache

A few improvement to typescript README template, including change from https://github.com/onfido/onfido-node/pull/141.

Fix examples in templated README in typescript

---

.github/workflows/update-specs-and-client-libraries.yaml

We've realised in commit https://github.com/onfido/onfido-node/pull/143/commits/52aad0a7a94e0af3616cddfc91c50a40298886a2 that some hidden files were surpresly missing.
This fix is to avoid bad consequences from breaking change to `actions/upload-artifact` announced below:
https://github.com/actions/upload-artifact/issues/602

Update workflow to include hidden file in archived artifacts

---

schemas/sdk_token/definitions.yaml

Looking at the mobile sdk docs [here](https://documentation.onfido.com/sdk/react-native/9.0.0/#3-configuring-sdk-with-tokens)
The application_id field of sdk_token does not seem to be a UUID:
> The application_id is the "Application ID" or "Bundle ID" that was already set up during development.
> For iOS this is usually in the form of com.your-company.app-name.
> To get this value manually, open xcode ios/YourProjectName, click on the project root, click the General tab, under Targets click your project name, and check the Bundle Identifier field.
> To get this value programmatically in native iOS code, see [Stack Overflow Page](https://stackoverflow.com/questions/8873203/how-to-get-bundle-id).
> For Android this is usually in the form of com.example.yourapp.
> To get this file manually, …

SDK Token: Remove UUID format from application_id.

---

schemas/reports/watchlist_aml_properties.yaml
schemas/reports/watchlist_enhanced_properties.yaml
schemas/reports/watchlist_standard_properties.yaml

Correct the type of `records`  in reports below from string to object:
-  watchlist_aml
- watchlist_enhanced
- watchlist_standard
- watchlist_peps_only
- watchlist_sanctions_only

[CAT-1376] Fix records item type in watchlist reports properties

---

schemas/reports/watchlist_aml_properties.yaml
schemas/reports/watchlist_enhanced_properties.yaml
schemas/reports/watchlist_standard_properties.yaml

Reflecting in our OpenAPI specification what is in our public documentation:
https://documentation.onfido.com/api/latest/#records-1
It completes and partially revert changes (not released yet) from https://github.com/onfido/onfido-openapi-spec/pull/118.

[CAT-1376] Add record item object definition for watchlist enhanced properties field

---

schemas/checks/definitions.yaml
schemas/reports/device_intelligence_breakdown.yaml
schemas/reports/watchlist_aml_properties.yaml
schemas/reports/watchlist_standard_properties.yaml

Completing change in https://github.com/onfido/onfido-openapi-spec/pull/125, in which `privacy_notices_read_consent_given` has been defined only among response properties.
Taking the opportunity for removing a few fields which has been deprecated since a while and deprecating others.

[CAT-1379] Fix check creation, remove some deprecated properties and deprecate others

---

schemas/webhooks/webhook_event.yaml

Removing duplicated enum as python library is [not happy about that](https://github.com/onfido/onfido-python/actions/runs/11404147149/job/31732689053).

[CAT-1306] Remove duplicated values from webhook event object status

---

schemas/reports/document_properties.yaml

Change barcode field in report properties from list to object for reports below:
- document
- document_video
- document_video_with_address_information
- document_with_address_information
- document_with_driver_verification
- document_with_driving_licence_information
- us_driving_licence
Change will be delivered in a minor release since this barcode property was completely broken and therefore it should not impact anyone

[CAT-1528] Fix barcode field in document properties object

---

schemas/reports/definitions.yaml
schemas/reports/facial_similarity_motion_report.yaml
schemas/reports/facial_similarity_photo_fully_auto_report.yaml
schemas/reports/facial_similarity_photo_report.yaml
schemas/reports/facial_similarity_video_report.yaml
schemas/reports/report_media.yaml

Facial similarity reports (Photo, Video, Motion) now include the biometric media in their response.

feat: add new fields to facial similarity report objects

---

schemas/reports/document_properties.yaml

Reverts onfido/onfido-openapi-spec#132

[CAT-1581] Revert "[CAT-1528] Fix barcode field in document properties object"

---

paths/workflow_runs.yaml

Reverts onfido/onfido-openapi-spec#136
Reverting this change for now as it's causing a breaking change on in java client library, i.e.:
```
-    public List<WorkflowRun> listWorkflowRuns(Integer page, String status, OffsetDateTime createdAtGt, OffsetDateTime createdAtLt, String sort) throws ApiException {
-        ApiResponse<List<WorkflowRun>> localVarResp = listWorkflowRunsWithHttpInfo(page, status, createdAtGt, createdAtLt, sort);
+    public List<WorkflowRun> listWorkflowRuns(Integer page, String status, OffsetDateTime createdAtGt, OffsetDateTime createdAtLt, String 
sort, UUID applicantId) throws ApiException {
+        ApiResponse<List<WorkflowRun>> localVarResp = listWorkflowRunsWithHttpInfo(page, status, createdAtGt, createdAtLt, sort, applicantId);
```
A new PR will be submitted …

Revert "add applicant_id in GET /workflow_runs"

---

schemas/tasks/task.yaml
schemas/webhooks/webhook_event.yaml
shell/sync-lib.sh

By removing the property type, it becomes a `Any` type, meaning that it can be anything as expected.
NB: small sed patch as in python otherwise it would remain `Optional[List[StrictStr]]` instead of `Any`: this change should be pushed to openapi generator (https://github.com/OpenAPITools/openapi-generator/blob/899ddecdbdb9b157ebbf3efbcfdf95ad7cf9740e/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonPydanticV1Codegen.java#L949).

[CAT-1590] Allow any type for the workflow task output

---

openapi.yaml
paths/workflow_runs.yaml

This PR adds the ability to download the Workflow Run Evidence Folder.
For more information about the product: https://documentation.onfido.com/api/latest/#retrieve-workflow-run-evidence-folder

[STUDIO-4305] Add download evidence folder path

---

generators/python/urllib3/templates/pyproject.mustache

With the upgrade to 2.0 it's now possible to use Poetry for dependency management and packaging so we need to set the package mode:
https://python-poetry.org/docs/basic-usage/#operating-modes
This change was used in the last release but committed directly in the release branch: https://github.com/onfido/onfido-python/pull/78

Use Poetry only for dependecy management

---

generators/python/urllib3/templates/webhook_event_verifier.py

The rest of the Python client is typed, but webhook_event_verifier.py is not.

Add missing type annotations to python webhook verifier

---

schemas/webhooks/webhook_event.yaml

In `audit_log.created` events, `payload.object` does not have an `href` property.
---
Library: onfido-python
Version: 4.6.0
Received webhook body:
```json
{
"payload": {
"resource_type": "audit_log",
"action": "audit_log.created",
"object": {
"id": "...",
"activity": "view_workflow_run",
"category": "workflow_results",
"created_at_iso8601": "2025-01-24T19:07:33Z",
"user": {
"email": "ollie@karoo.ca",
"full_name": "Oliver Lambson",
"ip_address": "..."
}
}
}
}
```
```py
from onfido.models import WebhookEvent
WebhookEvent.from_json(raw_event)
```
```
Traceback (most recent call last):
File ...
File "/karoo/.venv/lib/python3.13/site-packages/onfido/webhook_event_verifier.py", line 27, in read_payload
return WebhookEvent.from_json(raw_event)
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
File …
```

Denote webhook event payload.object.href as a not required property

---

generators/java/okhttp-gson/templates/libraries/okhttp-gson/ApiClient.mustache

passing meaningful information into an exception when deserialisation goes wrong.
The current message looked like this:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_OBJECT at path $.records[0]
We need to get more info to figure out what's the actual issue.

Show additional information on JSON decoding issue in Java client library

---

schemas/webhooks/definitions.yaml

Drop `workflow_signed_evidence_file.created` form webhook event type
NB: it requires a major release

[CAT-1593] Drop invalid enum value from webhook event type

---

generators/ruby/faraday/templates/SHA256SUM
generators/ruby/faraday/templates/api_client.mustache

Template has added to add line below: 
```ruby
require 'pathname'  {{! Added import }}
```
The original file from the generator is available [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/ruby-client/api_client.mustache).
This fix should be pushed upstream, the bug is consequence of this fix:
https://github.com/OpenAPITools/openapi-generator/pull/18243
fixing this other:
https://github.com/OpenAPITools/openapi-generator/pull/17853

Add missing import ApiClient in ruby client library

---

openapi.yaml
paths/documents.yaml

Add the missing download-nfc-face endpoint (`/documents/{document_id}/nfc_face`) to the OpenAPI spec.
[Link to Onfido API reference](https://documentation.onfido.com/api/latest/#download-nfc-face)

[DOCCAP-2513] Add download-nfc-face endpoint

---

schemas/reports/watchlist_aml_properties.yaml
schemas/reports/watchlist_standard_properties.yaml

The deprecated `records` property can be a list of objects, therefore type should not be imposed to string.

[CAT-1719] Don't impose a type on deprecated records property in watchlist reports

---

generators/java/okhttp-gson/templates/WebhookEventVerifier.mustache

This is to not catch `JsonParseException` and re-trow that as an `OnfidoInvalidSignatureError` when verifying webhooks events in onfido java.
NB: this change need a major release.

[CAT-1728] Don't catch JSON decoding error on webhook event verification in Java

---

schemas/reports/document_properties.yaml

Fixing the definition of `document_with_driving_licence_information` property since it's not an object but a list of objects.
This is consistent with the documention: https://documentation.onfido.com/api/latest/#document-with-driving-licence-information

[CAT-1911] Fix document_with_driving_licence_information to be a list of objects

---

schemas/reports/device_intelligence_breakdown.yaml

The `device_fingerprint_reuse` field was supposed to be an integer. The number of times will always not have a decimal part.
But because of GRPC conversions in `result-store` we are storing this value as a float. It is not trivial to fix this. And on openapi, a float value can be represented as having a decimal part or not (it is optional), i.e. both `3` and `3.0` are valid.
So it is much easier to fix this issue on the field by saying the field is a float. Results will be valid when they are without decimal part, but will also be valid when the api returns `0.0`.

Fix storage of device_fingerprint_reuse field as float

---

schemas/reports/device_intelligence_properties.yaml

The `device_fingerprint_reuse` properties field was supposed to be an integer. The number of times will always not have a decimal part.
We already fix this issue for this field in the "breakdowns". This fixes it for properties.

Fix storage of device_fingerprint_reuse properties as float

---

.github/workflows/update-specs-and-client-libraries.yaml
openapi.yaml

Update the Postman collection UUID since previous one can't be used anymore.
Take the opportunity to add the Public in the OpenAPI spec, to have that propagated to the Onfido collection.

[CAT-2289] Update the Postman collection UUID
